# Generated by Django 4.0.4 on 2022-07-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0002_tag_myproject_vote_total_review_myproject_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproject',
            name='vote_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
